### ISSUE TITLE
Coloring

### ISSUE THREAD

**Issue by wolffparkinson** [cs91chris/flask_logify#4]
Is it currently possible to use coloring with the Flask-Logify ?

I have tried these two options but have shortcoming in both: 

### 1. colored-logs
A famous external python [package](https://coloredlogs.readthedocs.io/en/latest/) commonly used for coloring logs.
Issue : After installing it on top of Flask-Logify, we loose all the formatting from Flask-Logify

### 2. ANSI escape characters
```yaml
format: \x1b[91m"[%(asctime)s] [%(levelname)s] : %(message)s"\x1b[0m
```
This does produce a colored log, but the issue is, there is nothing like Rotating**Stream**Handler
So, with the following YAML configuration, logs are duplicated in the console
```yaml
formatters:
  humanDebug:
    (): flask_logify.formatters.RequestFormatter
    format: \x1b[91m"[%(asctime)s] [%(levelname)s] : %(message)s"\x1b[0m
  humanInfo:
    (): flask_logify.formatters.RequestFormatter
    format: \x1b[93m"[%(asctime)s] [%(levelname)s] : %(message)s"\x1b[0m

handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout

  consoleDebug:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: humanDebug
    level: DEBUG

  consoleInfo:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: humanInfo
    level: INFO

loggers:
  flask-development:
    handlers: [ consoleDebug,consoleInfo,consoleWarn]
    level: DEBUG
    propogate: yes
```
